name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -t codesoom-cicd .
          docker tag codesoom-cicd rhkrgudwh/codesoom-cicd:${GITHUB_SHA::7}
          docker push rhkrgudwh/codesoom-cicd:${GITHUB_SHA::7}
